spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maciejscislowski/spring-cloud-microservices
          search-paths: configuration

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/